name: Auto Update README

on:
  schedule:
    - cron: "0 8 * * *"   # daily 08:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # <-- crucial

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with current date
        run: |
          cp README.md temp.md
          echo "" >> temp.md
          echo "---" >> temp.md
          echo "🕒 Auto-updated by GitHub Actions on $(date -u)" >> temp.md
          mv temp.md README.md

      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git add README.md
          # If nothing changed, exit cleanly (prevents exit 128)
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "Auto update README"
          git push origin HEAD:main
